title: "Connor Winters"
author: "Connor Winters"
description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "About", file: "about.md"}
  - {title: "Resume", file: "resume.md"}
  - {title: "Projects", file: "projects.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:connor.winters1017@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/connormw"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/connor-winters-758a53203/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
